function [alpha,dt_mpc] = check_controllability(x0,cpl,T,dt)

%% Estimate exponential controllability constants
%
% Computes the overshoot constant C and decay rate lambda from an
% open-loop trajectory generated by the centralized OCP.
%
% Following Reble (2012), these constants are used to estimate the
% nominal MPC contraction factor alpha for a given sampling time dt_mpc.

% Candidate MPC update period used in the theoretical contraction estimate
dt_mpc = 0.1;

%% Compute candidate trajectory used for controllability verification
N_cand = T/dt;
t = linspace(0,T,N_cand+1);
[X1,X2,X3,U1,U2,U3,~,~,~,~] = solve_central_ocp(cpl,x0,N_cand,dt);

%% Check exponential controllability (cf. Reble 2012)
z_mod = [X1;X2;X3;U1;U2;U3];

% Running cost accumulated along the candidate trajectory
l_integral = integral_cost_function(z_mod,N_cand);

% Stage-cost bound at the initial state (Q = I)
l_integral_0 = x0'*x0;

% Compute constants 
C = l_integral(1)/l_integral_0;                        % Overshoot constant

cost_tol = 1e-4;

% Ignore tail values dominated by numerical noise
n_est = find(l_integral(2:end) < cost_tol,1);

if isempty(n_est)
    n_est = N_cand;
end 

% Worst observed one-step contraction factor
ratios = l_integral(2:n_est) ./ l_integral(1:n_est-1);
C_cost = max(ratios);

if C_cost >= 1
    warning('No exponential decay detected in candidate trajectory.');
end

lambda = -log(C_cost)/dt;                              % exponential decay constant in exp(-lambda*t')*C*l_integral_0


%% MPC contraction estimate

Xi = 1 / (1 - ((exp(lambda*dt_mpc)-1) ...
     /(exp(lambda*T)-1))^(1/C));

gamma = 1 / (((1 - exp(-lambda*T)) ...
        /(exp(-lambda*dt_mpc)-exp(-lambda*T)))^(1/C) - 1);

alpha = 1 - gamma*(Xi-1);

if alpha<0
    warning('MPC not guarantueed to be stabilizing')
end 



end